export const FETCH_POPULAR_VIDEOS = 'FETCH_POPULAR_VIDEOS';
export const FETCH_VIDEOS_SUCCESS = 'FETCH_VIDEOS_SUCCESS';
export const FETCH_VIDEOS_FAILURE = 'FETCH_VIDEOS_FAILURE';
export const SAVE_VIDEO = 'SAVE_VIDEO';
export const EMPTY_SAVED_VIDEOS = 'EMPTY_SAVED_VIDEOS';